# Flask Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: pc-k8s
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: python:3.9
          workingDir: /resources/web
          env:
            - name: PROJECT_HOME
              value: /resources
          ports:
            - containerPort: 5001
          volumeMounts:
            - name: resources
              mountPath: /resources
          command:
            [
              "sh",
              "-c",
              "sleep 25 && pip install -r /resources/requirements.txt && python predict_flask.py",
            ]
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: resources
          hostPath:
            path: /resources
      restartPolicy: Always
