# Spark Worker 1 Service
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-2-svc
  namespace: pc-k8s
spec:
  selector:
    app: spark-worker-2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
