# Spark Master Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: pc-k8s
  labels:
    app: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      enableServiceLinks: false
      containers:
        - name: spark-master
          image: spark-master-custom:3.5.3
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master \
              --host $(SPARK_MASTER_HOST) \
              --port 7077 \
              --webui-port 8080
          ports:
            - containerPort: 8080
            - containerPort: 7077
          env:
            - name: SPARK_MODE
              value: "master"
            - name: SPARK_MASTER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
          resources:
            requests:
              memory: "512M"
              cpu: "0.5"
            limits:
              memory: "768Mi"
              cpu: "1"
      restartPolicy: Always
